Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../organizations/ordererOrganizations/charity.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.charity.com:7050
  - &Charityorg
    Name: CharityorgMSP
    ID: CharityorgMSP
    MSPDir: ../organizations/peerOrganizations/charityorg.charity.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('CharityorgMSP.admin', 'CharityorgMSP.peer', 'CharityorgMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('CharityorgMSP.admin', 'CharityorgMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('CharityorgMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('CharityorgMSP.peer')"
  - &Donar
    Name: DonarMSP
    ID: DonarMSP
    MSPDir: ../organizations/peerOrganizations/donar.charity.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('DonarMSP.admin', 'DonarMSP.peer', 'DonarMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('DonarMSP.admin', 'DonarMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('DonarMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('DonarMSP.peer')"

  - &Auditor
    Name: AuditorMSP
    ID: AuditorMSP
    MSPDir: ../organizations/peerOrganizations/auditor.charity.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('AuditorMSP.admin', 'AuditorMSP.peer', 'AuditorMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('AuditorMSP.admin', 'AuditorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('AuditorMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('AuditorMSP.peer')"

Capabilities:  
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true
    
Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  Addresses:
    - orderer.charity.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  ThreeOrgsChannel:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
          - Host: orderer.charity.com
            Port: 7050
            ClientTLSCert: ../organizations/ordererOrganizations/charity.com/orderers/orderer.charity.com/tls/server.crt
            ServerTLSCert: ../organizations/ordererOrganizations/charity.com/orderers/orderer.charity.com/tls/server.crt
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Charityorg
        - *Donar
        - *Auditor
      Capabilities: *ApplicationCapabilities