#!/bin/bash

function createCharityorg() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/charityorg.charity.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/charityorg.charity.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-charityorg --tls.certfiles "${PWD}/organizations/fabric-ca/charityorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-charityorg.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-charityorg.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-charityorg.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-charityorg.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/charityorg.charity.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy charityorg's CA cert to charityorg's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/charityorg.charity.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/charityorg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/charityorg.charity.com/msp/tlscacerts/ca.crt"

  # Copy charityorg's CA cert to charityorg's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/charityorg.charity.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/charityorg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/charityorg.charity.com/tlsca/tlsca.charityorg.charity.com-cert.pem"

  # Copy charityorg's CA cert to charityorg's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/charityorg.charity.com/ca"
  cp "${PWD}/organizations/fabric-ca/charityorg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/charityorg.charity.com/ca/ca.charityorg.charity.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-charityorg --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/charityorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-charityorg --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/charityorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-charityorg --id.name charityorgadmin --id.secret charityorgadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/charityorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-charityorg -M "${PWD}/organizations/peerOrganizations/charityorg.charity.com/peers/peer0.charityorg.charity.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/charityorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/charityorg.charity.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/charityorg.charity.com/peers/peer0.charityorg.charity.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-charityorg -M "${PWD}/organizations/peerOrganizations/charityorg.charity.com/peers/peer0.charityorg.charity.com/tls" --enrollment.profile tls --csr.hosts peer0.charityorg.charity.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/charityorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/charityorg.charity.com/peers/peer0.charityorg.charity.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/charityorg.charity.com/peers/peer0.charityorg.charity.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/charityorg.charity.com/peers/peer0.charityorg.charity.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/charityorg.charity.com/peers/peer0.charityorg.charity.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/charityorg.charity.com/peers/peer0.charityorg.charity.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/charityorg.charity.com/peers/peer0.charityorg.charity.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-charityorg -M "${PWD}/organizations/peerOrganizations/charityorg.charity.com/users/User1@charityorg.charity.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/charityorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/charityorg.charity.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/charityorg.charity.com/users/User1@charityorg.charity.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://charityorgadmin:charityorgadminpw@localhost:7054 --caname ca-charityorg -M "${PWD}/organizations/peerOrganizations/charityorg.charity.com/users/Admin@charityorg.charity.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/charityorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/charityorg.charity.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/charityorg.charity.com/users/Admin@charityorg.charity.com/msp/config.yaml"
}

function createDonar() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/donar.charity.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/donar.charity.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-donar --tls.certfiles "${PWD}/organizations/fabric-ca/donar/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-donar.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-donar.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-donar.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-donar.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/donar.charity.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy donar's CA cert to donar's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/donar.charity.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/donar/ca-cert.pem" "${PWD}/organizations/peerOrganizations/donar.charity.com/msp/tlscacerts/ca.crt"

  # Copy donar's CA cert to donar's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/donar.charity.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/donar/ca-cert.pem" "${PWD}/organizations/peerOrganizations/donar.charity.com/tlsca/tlsca.donar.charity.com-cert.pem"

  # Copy donar's CA cert to donar's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/donar.charity.com/ca"
  cp "${PWD}/organizations/fabric-ca/donar/ca-cert.pem" "${PWD}/organizations/peerOrganizations/donar.charity.com/ca/ca.donar.charity.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-donar --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/donar/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-donar --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/donar/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-donar --id.name donaradmin --id.secret donaradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/donar/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-donar -M "${PWD}/organizations/peerOrganizations/donar.charity.com/peers/peer0.donar.charity.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/donar/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/donar.charity.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/donar.charity.com/peers/peer0.donar.charity.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-donar -M "${PWD}/organizations/peerOrganizations/donar.charity.com/peers/peer0.donar.charity.com/tls" --enrollment.profile tls --csr.hosts peer0.donar.charity.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/donar/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/donar.charity.com/peers/peer0.donar.charity.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/donar.charity.com/peers/peer0.donar.charity.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/donar.charity.com/peers/peer0.donar.charity.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/donar.charity.com/peers/peer0.donar.charity.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/donar.charity.com/peers/peer0.donar.charity.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/donar.charity.com/peers/peer0.donar.charity.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-donar -M "${PWD}/organizations/peerOrganizations/donar.charity.com/users/User1@donar.charity.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/donar/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/donar.charity.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/donar.charity.com/users/User1@donar.charity.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://donaradmin:donaradminpw@localhost:8054 --caname ca-donar -M "${PWD}/organizations/peerOrganizations/donar.charity.com/users/Admin@donar.charity.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/donar/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/donar.charity.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/donar.charity.com/users/Admin@donar.charity.com/msp/config.yaml"
}


function createAuditor() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/auditor.charity.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/auditor.charity.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-auditor --tls.certfiles "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-auditor.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-auditor.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-auditor.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-auditor.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/auditor.charity.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy auditor's CA cert to auditor's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/auditor.charity.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem" "${PWD}/organizations/peerOrganizations/auditor.charity.com/msp/tlscacerts/ca.crt"

  # Copy auditor's CA cert to auditor's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/auditor.charity.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem" "${PWD}/organizations/peerOrganizations/auditor.charity.com/tlsca/tlsca.auditor.charity.com-cert.pem"

  # Copy auditor's CA cert to auditor's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/auditor.charity.com/ca"
  cp "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem" "${PWD}/organizations/peerOrganizations/auditor.charity.com/ca/ca.auditor.charity.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-auditor --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-auditor --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-auditor --id.name auditoradmin --id.secret auditoradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-auditor -M "${PWD}/organizations/peerOrganizations/auditor.charity.com/peers/peer0.auditor.charity.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/auditor.charity.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/auditor.charity.com/peers/peer0.auditor.charity.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-auditor -M "${PWD}/organizations/peerOrganizations/auditor.charity.com/peers/peer0.auditor.charity.com/tls" --enrollment.profile tls --csr.hosts peer0.auditor.charity.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/auditor.charity.com/peers/peer0.auditor.charity.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/auditor.charity.com/peers/peer0.auditor.charity.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/auditor.charity.com/peers/peer0.auditor.charity.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/auditor.charity.com/peers/peer0.auditor.charity.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/auditor.charity.com/peers/peer0.auditor.charity.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/auditor.charity.com/peers/peer0.auditor.charity.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-auditor -M "${PWD}/organizations/peerOrganizations/auditor.charity.com/users/User1@auditor.charity.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/auditor.charity.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/auditor.charity.com/users/User1@auditor.charity.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://auditoradmin:auditoradminpw@localhost:11054 --caname ca-auditor -M "${PWD}/organizations/peerOrganizations/auditor.charity.com/users/Admin@auditor.charity.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/auditor/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/auditor.charity.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/auditor.charity.com/users/Admin@auditor.charity.com/msp/config.yaml"
}


function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/charity.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/charity.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/charity.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/charity.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/charity.com/msp/tlscacerts/tlsca.charity.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/charity.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/charity.com/tlsca/tlsca.charity.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/charity.com/orderers/orderer.charity.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/charity.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/charity.com/orderers/orderer.charity.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/charity.com/orderers/orderer.charity.com/tls" --enrollment.profile tls --csr.hosts orderer.charity.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/charity.com/orderers/orderer.charity.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/charity.com/orderers/orderer.charity.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/charity.com/orderers/orderer.charity.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/charity.com/orderers/orderer.charity.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/charity.com/orderers/orderer.charity.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/charity.com/orderers/orderer.charity.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/charity.com/orderers/orderer.charity.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/charity.com/orderers/orderer.charity.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/charity.com/orderers/orderer.charity.com/msp/tlscacerts/tlsca.charity.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/charity.com/users/Admin@charity.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/charity.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/charity.com/users/Admin@charity.com/msp/config.yaml"
}

createCharityorg
createDonar
createAuditor
createOrderer